"""Add pending to enum status in submissionhistory table

Revision ID: b17e5da498e8
Revises: f0ef164081cd
Create Date: 2025-12-17 10:25:03.945128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b17e5da498e8'
down_revision: Union[str, Sequence[str], None] = 'f0ef164081cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE submissionstatus ADD VALUE 'PENDING'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
