"""add comment column to TestCase

Revision ID: 7500743829b6
Revises: 4a1aefd5c2f3
Create Date: 2025-12-06 16:49:03.432812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7500743829b6'
down_revision: Union[str, Sequence[str], None] = '4a1aefd5c2f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_case', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_case', 'comment')
    # ### end Alembic commands ###
