"""Add description column in CourseModel

Revision ID: f031d232305f
Revises: b17e5da498e8
Create Date: 2025-12-31 12:50:34.384826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f031d232305f'
down_revision: Union[str, Sequence[str], None] = 'b17e5da498e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('description', sa.Text(), nullable=False, server_default=''))
    op.alter_column('course', 'description', server_default=None)
    op.alter_column('unit', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unit', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('course', 'description')
    # ### end Alembic commands ###
