"""Create HintView table and move errorlog column from submissionHistory to submissionResult

Revision ID: f0ef164081cd
Revises: 7500743829b6
Create Date: 2025-12-17 09:45:25.569685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0ef164081cd'
down_revision: Union[str, Sequence[str], None] = '7500743829b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hint_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hint_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hint_id'], ['hint.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hint_view_id'), 'hint_view', ['id'], unique=False)
    op.drop_column('submission_history', 'error_log')
    op.add_column('submission_result', sa.Column('error_log', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission_result', 'error_log')
    op.add_column('submission_history', sa.Column('error_log', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_hint_view_id'), table_name='hint_view')
    op.drop_table('hint_view')
    # ### end Alembic commands ###
